name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup credentials
        run: |
          mkdir ~/.ivy2 && echo "$IVY2_CREDENTIALS" >> ~/.ivy2/.credentials
        shell: bash
        env:
          IVY2_CREDENTIALS: ${{secrets.IVY2_CREDENTIALS}}
      - name: Build archive
        run: sbt 'test' 'set packageName in Universal := "archive"' 'universal:packageZipTarball'
      - uses: actions/upload-artifact@v2
        with:
          name: igeolise-downloader-status-archive
          path: target/universal/archive.tgz
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v1
        with:
          username: ${{secrets.DOCKER_HUB_USER}}
          password: ${{secrets.DOCKER_HUB_PASSWORD}}
      - name: Download built archive
        uses: actions/download-artifact@v1
        with:
          name: igeolise-downloader-status-archive
      - shell: bash
        run: |
          mkdir -p ~/.ansible/igeolise-secrets
          echo $ANSIBLE_VAULT_PASSWORD > ~/.ansible/igeolise-secrets/vault-psw
        env:
          ANSIBLE_VAULT_PASSWORD: ${{secrets.ANSIBLE_VAULT_PASSWORD}}
      - name: Docker stuff
        shell: bash
        run: |
          cd igeolise-ansible
          ls -l
        uses: docker://igeolise/ansible:latest